# Assignment 4: Data Wrangling
```
Course: ENV 700 - Environmental Data Exploration
Author: Student Name
Date: Fall 2026
```

This notebook accompanies the Python lessons on **Data Wrangling**, the second stage in the data analytics pipeline: **exploration, wrangling, analysis, and visualization**.

In this notebook, you will be working with US EPA Air Quality System (AQS) data on ozone and fine particulate matter (2.5 mm) levels recorded at its North Carolina monitoring stations for the years 2024 and 2025. The raw data files are provided as four separate CSV files: one for each pollutant-year combination. In this exercise, you will import each and wrangle them separately so that they can be combined into a single dataframe, where additional wrangling will enable comprehensive analysis of the dataset.

---
### 1. Set up your Python Session

#### ✅ 1.1 Import Packages
* Load the pathlib Path object and the Pandas package into your coding environnment

In [2]:
# 1.1 Import Packages
from pathlib import Path
import pandas as pd

#### ✅ 1.2 Set project folder variables
* Create three Path variables, one set to your project's **root folder** one set to the **raw data folder** and another to the **processed data folder**. 
* Display the the values of these three variables in your notebook.

In [3]:
# 1.2 Set project folders using relative paths
project_fldr = Path.cwd().parent
raw_fldr = project_fldr / 'data' / 'raw'
processed_fldr = project_fldr / 'data' / 'processed'
raw_fldr

PosixPath('/Users/masonbunker/Desktop/Duke/Environmental Data Exploration/ENVR700/data/raw')

#### ✅ 1.3 Set a path to the raw data files
* Create a Path variable pointing to the four EPA AQS files found in the raw data folder: 
    - `EPAair_O3_NC2024_raw.csv`
    - `EPAair_O3_NC2025_raw.csv`
    - `EPAair_PM25_NC2024_raw.csv`
    - `EPAair_PM25_NC2025_raw.csv`

In [4]:
# 1.3 Create file path variables
Ozone2024_RawFile = raw_fldr / "EPAair_O3_NC2024_raw.csv"
Ozone2025_RawFile = raw_fldr / "EPAair_O3_NC2025_raw.csv"
PM25_2024_RawFile = raw_fldr / "EPAair_PM25_NC2024_raw.csv"
PM25_2025_RawFile = raw_fldr / "EPAair_PM25_NC2025_raw.csv"

print(Ozone2024_RawFile.exists(), Ozone2024_RawFile)
print(Ozone2025_RawFile.exists(), Ozone2025_RawFile)
print(PM25_2024_RawFile.exists(), PM25_2024_RawFile)
print(PM25_2025_RawFile.exists(), PM25_2025_RawFile)

True /Users/masonbunker/Desktop/Duke/Environmental Data Exploration/ENVR700/data/raw/EPAair_O3_NC2024_raw.csv
True /Users/masonbunker/Desktop/Duke/Environmental Data Exploration/ENVR700/data/raw/EPAair_O3_NC2025_raw.csv
True /Users/masonbunker/Desktop/Duke/Environmental Data Exploration/ENVR700/data/raw/EPAair_PM25_NC2024_raw.csv
True /Users/masonbunker/Desktop/Duke/Environmental Data Exploration/ENVR700/data/raw/EPAair_PM25_NC2025_raw.csv

#### ✅ 1.4 Read the four files into separate dataframes
(*No need to set data types, parse dates, or perform any other specialize import functions here; we will wrangle value later.*)

In [5]:
# 1.4 Read data into dataframes
Ozone_24 = pd.read_csv(Ozone2024_RawFile)
Ozone_25 = pd.read_csv(Ozone2025_RawFile)
PM25_24 = pd.read_csv(PM25_2024_RawFile)
PM25_25 = pd.read_csv(PM25_2025_RawFile)

#### ✅ 1.5 Report the dimensions of each dataframe
🔥***TIP***: *Each dataframe should have a different number of records.*

In [6]:
# 1.5 Report the dimensions of each dataset

print("Dataframe Sizes")
print("Ozone 2024:",Ozone_24.shape)
print("Ozone 2025:", Ozone_25.shape)
print("PM2.5 2024:", PM25_24.shape)
print("PM2.5 2025:", PM25_25.shape)

Dataframe Sizes
Ozone 2024: (9519, 21)
Ozone 2025: (9466, 21)
PM2.5 2024: (9752, 22)
PM2.5 2025: (10184, 22)

---
### 2. Wrangle individual datasets

In [7]:
PM25_24

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,Units,Daily AQI Value,Local Site Name,Daily Obs Count,Percent Complete,...,Method Code,Method Description,CBSA Code,CBSA Name,State FIPS Code,State,County FIPS Code,County,Site Latitude,Site Longitude
0,01/01/2024,AQS,370110002,1,2.6,ug/m3 LC,14,Linville Falls,1,100.0,...,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
1,01/04/2024,AQS,370110002,1,2.4,ug/m3 LC,13,Linville Falls,1,100.0,...,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
2,01/07/2024,AQS,370110002,1,0.9,ug/m3 LC,5,Linville Falls,1,100.0,...,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
3,01/10/2024,AQS,370110002,1,1.1,ug/m3 LC,6,Linville Falls,1,100.0,...,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
4,01/13/2024,AQS,370110002,1,2.0,ug/m3 LC,11,Linville Falls,1,100.0,...,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9747,12/27/2024,AQS,371830021,3,10.0,ug/m3 LC,53,Triple Oak,1,100.0,...,209,Met One BAM-1022 Mass Monitor w/ VSCC or TE-PM...,39580.0,"Raleigh, NC",37,North Carolina,183,Wake,35.865200,-78.819700
9748,12/28/2024,AQS,371830021,3,8.1,ug/m3 LC,45,Triple Oak,1,100.0,...,209,Met One BAM-1022 Mass Monitor w/ VSCC or TE-PM...,39580.0,"Raleigh, NC",37,North Carolina,183,Wake,35.865200,-78.819700
9749,12/29/2024,AQS,371830021,3,2.9,ug/m3 LC,16,Triple Oak,1,100.0,...,209,Met One BAM-1022 Mass Monitor w/ VSCC or TE-PM...,39580.0,"Raleigh, NC",37,North Carolina,183,Wake,35.865200,-78.819700
9750,12/30/2024,AQS,371830021,3,2.4,ug/m3 LC,13,Triple Oak,1,100.0,...,209,Met One BAM-1022 Mass Monitor w/ VSCC or TE-PM...,39580.0,"Raleigh, NC",37,North Carolina,183,Wake,35.865200,-78.819700
9751,12/31/2024,AQS,371830021,3,5.5,ug/m3 LC,31,Triple Oak,1,100.0,...,209,Met One BAM-1022 Mass Monitor w/ VSCC or TE-PM...,39580.0,"Raleigh, NC",37,North Carolina,183,Wake,35.865200,-78.819700

#### ✅ 2.1 Update data types
* Convert the `Date` column in each dataframe so that values are datetime objects. 
* List the date range for the two Ozone dataframes.

In [8]:
# Convert the Date column to DateTime objects
# At first I attempted to created a function and I completely overcomplicated it, but that would be fun to do in the long run!

Ozone_24["Date"] = pd.to_datetime(Ozone_24["Date"], format="%m/%d/%Y")
Ozone_25["Date"] = pd.to_datetime(Ozone_25["Date"], format="%m/%d/%Y")
PM25_24["Date"] = pd.to_datetime(PM25_24["Date"], format="%m/%d/%Y")
PM25_25["Date"] = pd.to_datetime(PM25_25["Date"], format="%m/%d/%Y")

# checked all conversions using df.dtypes, all date columns changed formats successfully

# Print date ranges

print("Ozone 2024 min:",Ozone_24["Date"].min(), "Ozone 2024 max:", Ozone_24["Date"].max())
print("Ozone 2025 min:",Ozone_25["Date"].min(), "Ozone 2025 max:", Ozone_25["Date"].max())

Ozone 2024 min: 2024-01-01 00:00:00 Ozone 2024 max: 2024-12-30 00:00:00
Ozone 2025 min: 2025-01-01 00:00:00 Ozone 2025 max: 2025-12-31 00:00:00

#### ✅ 2.2 Eliminate unnecessary columns
* Subset each dataframe to include only the following columns:  
```'Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude'```

In [9]:
# 2.2 Subset columns
# Again, there should be a way to define a function to do this for all of them...

subset_cols = ['Date', 'Daily AQI Value', 
               'Local Site Name', 'AQS Parameter Description', 
               'County', 'Site Latitude', 'Site Longitude'
               ]

Ozone_24 = Ozone_24[subset_cols]
Ozone_25 = Ozone_25[subset_cols]
PM25_24 = PM25_24[subset_cols]
PM25_25 = PM25_25[subset_cols]

PM25_25
Ozone_24

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
0,2024-03-01,26,Taylorsville Liledoun,Ozone,Alexander,35.913800,-81.191000
1,2024-03-02,34,Taylorsville Liledoun,Ozone,Alexander,35.913800,-81.191000
2,2024-03-03,35,Taylorsville Liledoun,Ozone,Alexander,35.913800,-81.191000
3,2024-03-04,37,Taylorsville Liledoun,Ozone,Alexander,35.913800,-81.191000
4,2024-03-05,42,Taylorsville Liledoun,Ozone,Alexander,35.913800,-81.191000
...,...,...,...,...,...,...,...
9514,2024-09-20,61,Mt. Mitchell,Ozone,Yancey,35.765413,-82.264944
9515,2024-09-21,47,Mt. Mitchell,Ozone,Yancey,35.765413,-82.264944
9516,2024-09-22,46,Mt. Mitchell,Ozone,Yancey,35.765413,-82.264944
9517,2024-09-23,37,Mt. Mitchell,Ozone,Yancey,35.765413,-82.264944
9518,2024-09-24,37,Mt. Mitchell,Ozone,Yancey,35.765413,-82.264944

#### ✅ 2.3 Update values
* For the PM2.5 datasets, fill all cells in the `AQS Parameter Description` with the string "PM2.5".  
(*All cell values in this column will be identical.*)

In [10]:
# 2.3 Update values

PM25_24["AQS Parameter Description"] = "PM2.5"
PM25_25["AQS Parameter Description"] = "PM2.5"

---
### 3. Combine datasets

#### ✅ 3.1 Confirm dataframes are set to be merged
* Ensure that column names in each dataframe are indentical

In [11]:
# 3.1 Ensure column are same across all dataframes

print("These are the columns in each dataframe")
print("PM25_24:",PM25_24.columns)
print("PM25_25:",PM25_25.columns)
print("Ozone_24:", Ozone_24.columns)
print("Ozone_25:", Ozone_25.columns)

These are the columns in each dataframe
PM25_24: Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
PM25_25: Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Ozone_24: Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Ozone_25: Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')

#### ✅ 3.2 Combine the datasets 
* Combine the datasets using Pandas' `concat()` function
* Report the dimensions of the merged dataframe. (This should be `38,921 x 7`)

In [12]:
# 3.2 Concatentate & report shape
AQS = pd.concat(
    ([PM25_24, PM25_25, Ozone_24, Ozone_25]),
    ignore_index=True
)

AQS.shape

(38921, 7)

#### ✅ 3.3 Examine the contents of the merged dataframe
* Display a sample of 10 randomly selected rows, using the random state = 42

In [13]:
# 3.3 View a sample of data
AQS.sample(10, random_state=42)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
26921,2024-11-15,25,Candor,Ozone,Montgomery,35.263200,-79.836500
6483,2024-05-23,58,Candor: EPA CASTNet Site,PM2.5,Montgomery,35.263165,-79.836636
34315,2025-05-29,25,West Johnston Co.,Ozone,Johnston,35.590950,-78.462200
12494,2025-08-12,18,Durham Armory,PM2.5,Durham,36.032955,-78.904037
27781,2024-05-25,48,Bethany sch.,Ozone,Rockingham,36.308889,-79.859167
23089,2024-08-02,38,Union Cross,Ozone,Forsyth,36.051805,-80.144933
35024,2025-03-14,54,Coweeta,Ozone,Macon,35.060800,-83.430600
1157,2024-11-10,52,Hickory Water Tower,PM2.5,Catawba,35.728889,-81.365556
4178,2024-11-13,18,Mendenhall School,PM2.5,Guilford,36.109006,-79.802314
13592,2025-03-10,30,Clemmons Middle,PM2.5,Forsyth,36.026612,-80.341962

---
### 4. Wrangle the combined dataset

#### ✅ 4.1 Subset rows 
* Generate a list of local site names common to all 4 dataframes (code provided, but replace the dataframe names to match your own).
* Create a subset of the full dataset, selecting those that match these local site names.
* Report the dimensions of the resulting dataframe. (This should be `18,778 x 7`)

In [14]:
# Generate a list of local site names common to all 4 dataframes
## Create set objects from the values in the Local Site Name columns
sites_oz24 = set(Ozone_24['Local Site Name']) #<-- update dataframe name to use your 2024 Ozone dataframe
sites_oz25 = set(Ozone_25['Local Site Name'])
sites_pm24 = set(PM25_24['Local Site Name'])
sites_pm25 = set(PM25_25['Local Site Name'])
## Compute the intersection 
common_sites = sites_oz24 & sites_oz25 & sites_pm24 & sites_pm25
common_sites

{'Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.'}

In [74]:
# 4.1 Subset for records with sites in common
AQS_site_subset = AQS.loc[(AQS["Local Site Name"].isin(common_sites))]

AQS_site_subset.shape

(18778, 7)

#### ✅ 4.2 Group and summarize data 
We want a dataset that lists one record per measured pollutant per location per day. To ensure we have that, we'll group data by date, local site name, AQS parameter, and county, computing the mean daily AQI value as well as mean latitude and longitude value. 
* Group the data on the grouping variables mentioned above. 
* For each group, compute mean daily AQI value, mean latitude, and mean longitude. 
* Reset the index of the summarized dataset to restore the product to a flat dataframe.
* Report the dimensions of the dataset. (This should be `17,017 x 7`.)

In [16]:
# 4.2 Group and summarize data, then report its dimensions

AQS_summary = (
    AQS_site_subset
    .groupby(["Date", "Local Site Name", "AQS Parameter Description", "County"])
    .agg(
        AQI_mean = ("Daily AQI Value", "mean"),
        Lat_mean = ("Site Latitude", "mean"),
        Long_mean = ("Site Longitude", "mean")
    )
    .reset_index()
)

AQS_summary

,Date,Local Site Name,AQS Parameter Description,County,AQI_mean,Lat_mean,Long_mean
0,2024-01-01,Bryson City,PM2.5,Swain,43.0,35.434767,-83.442133
1,2024-01-01,Castle Hayne,PM2.5,New Hanover,44.5,34.364167,-77.838611
2,2024-01-01,Clemmons Middle,PM2.5,Forsyth,47.5,36.026612,-80.341962
3,2024-01-01,Durham Armory,PM2.5,Durham,61.0,36.032955,-78.904037
4,2024-01-01,Frying Pan Mountain,PM2.5,Haywood,14.0,35.379167,-82.792500
...,...,...,...,...,...,...,...
17012,2025-12-31,Millbrook School,PM2.5,Wake,24.0,35.856111,-78.574167
17013,2025-12-31,Pitt Agri. Center,PM2.5,Pitt,23.0,35.641276,-77.360126
17014,2025-12-31,Rockwell,Ozone,Rowan,35.0,35.551868,-80.395039
17015,2025-12-31,Rockwell,PM2.5,Rowan,21.0,35.551868,-80.395039
17016,2025-12-31,West Johnston Co.,PM2.5,Johnston,25.0,35.590950,-78.462200

#### ✅ 4.3 Add calculated columns
* Add `Year` and `Month` columns to your dataframe, deriving values from the `Date` field.

In [41]:
# 4.3 Calculate year and month columns
AQS_summary = (
    AQS_summary
    .assign(
        year=lambda df: df["Date"].dt.year,
        month=lambda df: df["Date"].dt.month,
    )
)

AQS_summary.head()

,Date,Local Site Name,AQS Parameter Description,County,AQI_mean,Lat_mean,Long_mean,year,month
0,2024-01-01,Bryson City,PM2.5,Swain,43.0,35.434767,-83.442133,2024,1
1,2024-01-01,Castle Hayne,PM2.5,New Hanover,44.5,34.364167,-77.838611,2024,1
2,2024-01-01,Clemmons Middle,PM2.5,Forsyth,47.5,36.026612,-80.341962,2024,1
3,2024-01-01,Durham Armory,PM2.5,Durham,61.0,36.032955,-78.904037,2024,1
4,2024-01-01,Frying Pan Mountain,PM2.5,Haywood,14.0,35.379167,-82.792500,2024,1

#### ✅ 4.4 Spread AQI values into separate columns: OZone & PM2.5
* Reshape our table so that Daily AQI values for Ozone and PM2.5 data appear in separate columns.
* Reset the index of the reshaped table to restore it as a flat dataframe.
* Display the first 5 records in the resulting dataframe

In [60]:
# 4.4 Spread data so Ozone, PM2.5 daily AQI valiues occupy separate columns

# I am slightly unsure if I understand this or not... I think it was a pivot table?
# do we keep the other column headings???????
index_cols = ["Date", "Local Site Name", "County", "Lat_mean", "Long_mean", "year", "month"]

AQS_daily_wide = (
    AQS_summary
    .pivot_table(
        index= index_cols,
        columns="AQS Parameter Description",
        values= "AQI_mean"  #i accidentally had this in [square brackets] 
                            #and that cause Ozone and PM2.5 to be multi-index
    )
    .reset_index()
)

AQS_daily_wide.head()

AQS Parameter Description,Date,Local Site Name,County,Lat_mean,Long_mean,year,month,Ozone,PM2.5
0,2024-01-01,Bryson City,Swain,35.434767,-83.442133,2024,1,NaN,43.0
1,2024-01-01,Castle Hayne,New Hanover,34.364167,-77.838611,2024,1,NaN,44.5
2,2024-01-01,Clemmons Middle,Forsyth,36.026612,-80.341962,2024,1,NaN,47.5
3,2024-01-01,Durham Armory,Durham,36.032955,-78.904037,2024,1,NaN,61.0
4,2024-01-01,Frying Pan Mountain,Haywood,35.379167,-82.792500,2024,1,NaN,14.0

---
## 5. Save your processed dataset

#### ✅ 5.1 Save the spread dataset to a file 
* Name the spread data file `EPAair_O3_PM25_NC2425_Processed.csv`
* Save it to your processed data folder
* Do not include the dataframe index in your saved file

In [75]:
# 5.1 Save the file
AQS_daily_wide.to_csv(
    processed_fldr/ "AQS_daily_wide.csv",
    index=False
)

---
## 6. Summarize and explore the data

#### ✅ 6.1 Generate a month summary table
* Group the above table to compute mean Ozone and PM2.5 values for each unique site, month, year combination. Be sure to reset the index of the product. 
* Display the first 5 records of this table.

In [72]:
# 6.1 Generate a summary table and show its first 5 records

AQS_monthly = (
    AQS_daily_wide
    .groupby(["Local Site Name", "year", "month"])
    .agg(
        n_records_Ozone = ("Ozone", "count"),
        Ozone_mean = ("Ozone", "mean"),
        n_records_PM = ("PM2.5", "count"),
        PM_mean = ("PM2.5", "mean")
    )
    .reset_index()
)

AQS_monthly.head()

,Local Site Name,year,month,n_records_Ozone,Ozone_mean,n_records_PM,PM_mean
0,Bryson City,2024,1,0,NaN,31,22.580645
1,Bryson City,2024,2,0,NaN,29,32.000000
2,Bryson City,2024,3,31,40.709677,31,30.935484
3,Bryson City,2024,4,29,43.793103,30,36.066667
4,Bryson City,2024,5,31,37.419355,31,30.387097

---
## 7. Submission
- Save, stage, and commit this notebook
- Push changes to your GitHub account
- Export as an HTML document
- Submit both your `.ipynb` and `.html` document to Canvas.